server:
  port: 8082
spring:
  application:
    name: DZ_5
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: "com.borisov.DZ_5.events.UserChangedEvent"
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
logging:
  level:
    root: INFO
topic:
  user-events: user-events-topic