spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # по умолчанию
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer  # для получения JSON
      properties:
        spring.json.trusted.packages: '*'   # нужно для JsonDeserialize
  mail:
    host: localhost
    port: 1025

topic:
  user-events: user-events-topic